/*
 * MainWindow.java
 *
 * Created on 17 April, 2010, 11:58 AM
 */
package com.contactReport.frame;

import javax.swing.JOptionPane;

/**
 *
 * @author  Sudipta
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultLookAndFeelDecorated(true);
        this.setTitle("Main Window");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuContact = new javax.swing.JMenu();
        mnuiAddContact = new javax.swing.JMenuItem();
        mnuiEditContact = new javax.swing.JMenuItem();
        mnuiViewAllContact = new javax.swing.JMenuItem();
        mnuGroup = new javax.swing.JMenu();
        mnuiAddGroup = new javax.swing.JMenuItem();
        mnuiExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnuContact.setText("Contact");

        mnuiAddContact.setText("Add New Contact");
        mnuiAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handelAddNewContact(evt);
            }
        });
        mnuContact.add(mnuiAddContact);

        mnuiEditContact.setText("Edit Contact Details");
        mnuiEditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handelEditContact(evt);
            }
        });
        mnuContact.add(mnuiEditContact);

        mnuiViewAllContact.setText("View All Contacts");
        mnuiViewAllContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handelViewAllContacts(evt);
            }
        });
        mnuContact.add(mnuiViewAllContact);

        jMenu1.add(mnuContact);

        mnuGroup.setText("Group");

        mnuiAddGroup.setText("Add New Group");
        mnuiAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handelAddNewGroup(evt);
            }
        });
        mnuGroup.add(mnuiAddGroup);

        jMenu1.add(mnuGroup);

        mnuiExit.setText("Exit");
        mnuiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handelExit(evt);
            }
        });
        jMenu1.add(mnuiExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handelEditContact(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handelEditContact
// TODO add your handling code here:
        EditContact editcontact = new EditContact();
        editcontact.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_handelEditContact

    private void handelAddNewContact(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handelAddNewContact
// TODO add your handling code here:
        AddContact contact = new AddContact();
        contact.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_handelAddNewContact

    private void handelExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handelExit
// TODO add your handling code here:
        int s = JOptionPane.showConfirmDialog(null, "Are you really want close the Program", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (s == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_handelExit

    private void handelViewAllContacts(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handelViewAllContacts
        // TODO add your handling code here:

        ViewAllContact viewAllContact = new ViewAllContact();
        viewAllContact.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_handelViewAllContacts

    private void handelAddNewGroup(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handelAddNewGroup
        // TODO add your handling code here:
        AddGroup addGroup=new AddGroup();
        addGroup.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_handelAddNewGroup

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*  java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new MainWindow().setVisible(true);
        }
        });*/

        Login login = new Login();
        login.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuContact;
    private javax.swing.JMenu mnuGroup;
    private javax.swing.JMenuItem mnuiAddContact;
    private javax.swing.JMenuItem mnuiAddGroup;
    private javax.swing.JMenuItem mnuiEditContact;
    private javax.swing.JMenuItem mnuiExit;
    private javax.swing.JMenuItem mnuiViewAllContact;
    // End of variables declaration//GEN-END:variables
}
